import { useEffect, useMemo, useState } from "react";
import { catalog } from "./data/catalog";
import { formatPhone, generateWhatsAppMessage } from "./utils/whatsapp";

type Cart = Record<string, number>;
const money = (n: number) => `R$ ${n.toFixed(2).replace(".", ",")}`;
const Mark = () => <span className="eyebrow">Vibe Afiações</span>;
const WhatsApp = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M17.5 14.4c-.3-.2-1.8-.9-2-.9-.3-.1-.5-.2-.7.1l-.9 1.2c-.2.2-.4.2-.7.1-1.8-.9-3-2.2-3.8-3.9-.1-.3 0-.5.1-.6l.5-.6c.2-.2.2-.4.3-.5.1-.2 0-.4 0-.5L9.2 7c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.1-.3-.2-.6-.3M12 22a9.8 9.8 0 0 1-5-1.4l-3.7 1 1-3.7a9.8 9.8 0 1 1 7.7 4.1m0-20a10.2 10.2 0 0 0-8.9 15.2L1.8 22l4.9-1.3A10.2 10.2 0 1 0 12 2"/></svg>;

function Header() { const [open,setOpen]=useState(false),[solid,setSolid]=useState(false); useEffect(()=>{const f=()=>setSolid(scrollY>32);addEventListener("scroll",f);return()=>removeEventListener("scroll",f)},[]); const links=[["#sobre","A Vibe"],["#servicos","Serviços"],["#catalogo","Valores"],["#solicitar","Solicitar"]]; return <header className={`header ${solid?"solid":""}`}><div className="shell nav"><a href="#inicio" className="brand"><img src="/logo.svg" alt=""/><span><b>Vibe Afiações</b><small>Qualidade e confiança</small></span></a><nav className="nav-links">{links.map(([h,l])=><a href={h} key={h}>{l}</a>)}</nav><a className="nav-button" href="#solicitar">Solicitar afiação</a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu"><i/><i/></button></div>{open&&<nav className="mobile-links">{links.map(([h,l])=><a href={h} key={h} onClick={()=>setOpen(false)}>{l}</a>)}</nav>}</header> }
function Hero(){return <section id="inicio" className="hero"><img src="/hero.jpg" alt="Profissional realizando afiação"/><div className="hero-filter"/><div className="shell hero-text"><p>Desde 2008 · Santa Catarina</p><h1>Afiação profissional para quem não abre mão da qualidade.</h1><span>Ferramentas bem cuidadas, prontas para voltar ao seu trabalho.</span><div><a className="button light" href="#solicitar">Solicitar afiação <b>→</b></a><a className="button outline" href="#sobre">Conheça a Vibe</a></div></div></section>}
function About(){return <section id="sobre" className="section"><div className="shell two-col about"><div className="photo"><img src="/tools.jpg" alt="Ferramentas da Vibe Afiações"/></div><div><Mark/><h2>Experiência no cuidado de cada ferramenta.</h2><p>Na Vibe Afiações, cada serviço é feito com atenção ao corte, ao acabamento e ao uso de cada peça. É trabalho de precisão para quem depende de uma boa ferramenta todos os dias.</p><div className="history"><strong>Desde <em>2008</em></strong><span><b>Qualidade e confiança.</b><br/>Uma história construída ferramenta por ferramenta.</span></div></div></div></section>}
function Services(){const list=["Alicates","Tesouras","Facas e cutelos","Lâminas","Espátulas"];return <section id="servicos" className="section soft"><div className="shell"><div className="heading"><div><Mark/><h2>O que a gente afia</h2></div><p>Atendimento cuidadoso para ferramentas de uso profissional e do dia a dia.</p></div><div className="service-list"><img src="/manicure.jpg" alt="Afiação de alicate de cutícula"/><ol>{list.map((x,i)=><li key={x}><small>0{i+1}</small>{x}</li>)}</ol></div></div></section>}
function Catalog(){return <section id="catalogo" className="section catalog"><div className="shell narrow"><Mark/><h2>Quanto custa afiar?</h2><p>Confira os valores de referência para cada ferramenta.</p><div className="prices"><div><small>Material</small><small>Preço</small></div>{catalog.map(x=><div key={x.id}><span>{x.name}</span><b>{money(x.price)}</b></div>)}</div><small className="note">O valor final pode variar após a avaliação da ferramenta.</small></div></section>}
function Request(){const [cart,setCart]=useState<Cart>({}),[name,setName]=useState(""),[phone,setPhone]=useState(""),[note,setNote]=useState(""),[errors,setErrors]=useState<Record<string,string>>({});const items=useMemo(()=>catalog.filter(x=>cart[x.id]).map(x=>({...x,qty:cart[x.id]})),[cart]);const total=items.reduce((a,x)=>a+x.price*x.qty,0);const change=(id:string,d:number)=>setCart(o=>{const n={...o},v=Math.max(0,(n[id]||0)+d);v?n[id]=v:delete n[id];return n});const send=()=>{const e:Record<string,string>={};if(!items.length)e.items="Selecione ao menos uma ferramenta.";if(!name.trim())e.name="Informe seu nome.";if(phone.replace(/\D/g,"").length<10)e.phone="Informe um WhatsApp válido.";setErrors(e);if(!Object.keys(e).length)open(generateWhatsAppMessage(items,{name,phone,note}),"_blank")};return <section id="solicitar" className="section request"><div className="shell"><div className="request-head"><Mark/><h2>Quais ferramentas você precisa afiar?</h2><p>Selecione os itens, informe as quantidades e envie o pedido pelo WhatsApp.</p></div><div className="order-grid"><div className="picker"><header><span>Ferramenta</span><span>Quantidade</span></header>{catalog.map(x=>{const q=cart[x.id]||0;return <div className={q?"picked":""} key={x.id}><p><b>{x.name}</b><small>{money(x.price)} por unidade</small></p><aside><button disabled={!q} onClick={()=>change(x.id,-1)}>−</button><output>{q}</output><button onClick={()=>change(x.id,1)}>+</button></aside></div>})}{errors.items&&<small className="error">{errors.items}</small>}</div><aside className="summary"><section><h3>Seu pedido</h3>{items.length?items.map(x=><p key={x.id}><span>{x.qty}x {x.name}</span><b>{money(x.qty*x.price)}</b></p>):<small>Os itens selecionados aparecem aqui.</small>}<div className="total"><span>Total estimado</span><b>{money(total)}</b></div></section><section className="form"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/></label>{errors.name&&<small className="error">{errors.name}</small>}<label>WhatsApp<input value={phone} onChange={e=>setPhone(formatPhone(e.target.value))} placeholder="(48) 99999-9999"/></label>{errors.phone&&<small className="error">{errors.phone}</small>}<label>Observação <small>(opcional)</small><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Algum detalhe sobre as ferramentas?"/></label><button className="button send" onClick={send}><WhatsApp/>Enviar solicitação pelo WhatsApp</button></section></aside></div></div></section>}
function Process(){const s=["Escolha suas ferramentas","Informe seus dados","Envie pelo WhatsApp","Combine o atendimento"];return <section className="section process"><div className="shell"><Mark/><h2>Um atendimento simples, do começo ao fim.</h2><div>{s.map((x,i)=><article key={x}><b>0{i+1}</b><p>{x}</p></article>)}</div></div></section>}
function Night(){return <section className="night"><img src="/night.jpg" alt="Atendimento noturno da Vibe Afiações"/><div/><article className="shell"><Mark/><h2>Agora também atendemos à noite.</h2><strong>19h às 22h</strong><p>Mais flexibilidade para você deixar suas ferramentas prontas para o trabalho.</p><a className="button outline" href="#solicitar">Solicitar afiação</a></article></section>}
function Footer(){return <footer><div className="shell"><a className="brand"><img src="/logo.svg" alt=""/><span><b>Vibe Afiações</b><small>Qualidade e confiança desde 2008</small></span></a><a href="https://wa.me/5548998408153" target="_blank" rel="noreferrer">(48) 99840-8153</a><small>© {new Date().getFullYear()} Vibe Afiações</small></div></footer>}
export default function App(){return <><Header/><main><Hero/><About/><Services/><Catalog/><Request/><Process/><Night/></main><Footer/></>}
